package:
  name:
  version:

source:
  path:
    ../

build:
  noarch: python
  script: python setup.py install --single_version-externally-managed --record=record.txt

requirements:
  host:
    - pip
    - python
  run:
    - python

about:
  license: BSD
  license_file: LICENSE
  summary:
